# hackish way to perform a riak rolling upgrade in a cluster
#
---
- hosts: riak_cluster
  serial: 1
  sudo: yes

  pre_tasks:
  - name: waiting (maybe) on transfers to complete
    riak: wait_for_handoffs=300 http_conn={{ inventory_hostname }}:8098

  tasks:
  - name: stopping riak
    service: name=riak state=stopped

  - name: upgrading riak
    apt: deb=/binaries/riak1412.deb dpkg_options='force-confold'

  - name: re.starting riak
    service: name=riak state=started

  - name: waiting for riak_kv
    riak: wait_for_service=kv http_conn={{ inventory_hostname }}:8098

  post_tasks:
  - name: node upgraded
    command: echo
