# simpler way to perform a rolling restart of a riak cluster
# optionally, you can wait for transfers to complete
#
---
- hosts: riak_cluster
  serial: 1
  sudo: yes

  pre_tasks:
  - name: waiting (maybe) on transfers to complete
    riak: wait_for_handoffs=300 http_conn={{ inventory_hostname }}:8098

  tasks:
  - name: restarting riak
    service: name=riak state=restarted
  - name: make sure riak is running
    service: name=riak state=running
  - name: waiting for riak_kv
    riak: wait_for_service=kv http_conn={{ inventory_hostname }}:8098

  post_tasks:
  - name: node restarted
    command: echo
